<?php

namespace Database\Seeders;

use App\Models\Contractor;
use Illuminate\Database\Seeder;

class ContractorSeeder extends Seeder
{
    public function run(): void
    {
        $contractors = [
            [
                'company_name' => 'Heartland Electrical Services',
                'contact_name' => 'Marcus Webb',
                'phone' => '402-555-0101',
                'phone_secondary' => '402-555-0102',
                'email' => 'marcus@heartlandelectrical.com',
                'address' => '1240 N 27th St, Lincoln, NE 68503',
                'specialty' => 'Electrical',
                'insurance_company' => 'State Farm',
                'has_construction_license' => true,
                'license_number' => 'NE-EL-40821',
                'notes' => 'Preferred electrician — fast response time.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Prairie Plumbing Co.',
                'contact_name' => 'David Ruiz',
                'phone' => '402-555-0201',
                'phone_secondary' => null,
                'email' => 'david@prairieplumbing.com',
                'address' => '500 S 10th St, Lincoln, NE 68508',
                'specialty' => 'Plumbing',
                'insurance_company' => 'Travelers',
                'has_construction_license' => true,
                'license_number' => 'NE-PL-31174',
                'notes' => null,
                'is_active' => true,
            ],
            [
                'company_name' => 'Great Plains HVAC',
                'contact_name' => 'Tom Fischer',
                'phone' => '402-555-0301',
                'phone_secondary' => '402-555-0302',
                'email' => 'tom@greatplainshvac.com',
                'address' => '3200 Cornhusker Hwy, Lincoln, NE 68504',
                'specialty' => 'HVAC',
                'insurance_company' => 'Liberty Mutual',
                'has_construction_license' => true,
                'license_number' => 'NE-HV-55029',
                'notes' => 'Also handles ductwork and ventilation.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Omaha Roofing Experts',
                'contact_name' => 'Brian Callahan',
                'phone' => '402-555-0401',
                'phone_secondary' => null,
                'email' => 'brian@omaharoofing.com',
                'address' => '7800 W Dodge Rd, Omaha, NE 68114',
                'specialty' => 'Roofing',
                'insurance_company' => 'Nationwide',
                'has_construction_license' => true,
                'license_number' => 'NE-RF-18843',
                'notes' => null,
                'is_active' => true,
            ],
            [
                'company_name' => 'Lincoln Concrete Works',
                'contact_name' => 'Jorge Medina',
                'phone' => '402-555-0501',
                'phone_secondary' => '402-555-0502',
                'email' => 'jorge@lincolnconcrete.com',
                'address' => '1900 W Van Dorn St, Lincoln, NE 68522',
                'specialty' => 'Concrete',
                'insurance_company' => 'Zurich',
                'has_construction_license' => true,
                'license_number' => 'NE-CN-77412',
                'notes' => 'Does driveways, slabs, and foundations.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Cornhusker Framing LLC',
                'contact_name' => 'Steve Harmon',
                'phone' => '402-555-0601',
                'phone_secondary' => null,
                'email' => 'steve@cornhuskerframing.com',
                'address' => '4510 NW 48th St, Lincoln, NE 68524',
                'specialty' => 'Framing',
                'insurance_company' => 'CNA',
                'has_construction_license' => true,
                'license_number' => 'NE-FR-20093',
                'notes' => null,
                'is_active' => true,
            ],
            [
                'company_name' => 'Bluegrass Drywall & Paint',
                'contact_name' => 'Amanda Porter',
                'phone' => '402-555-0701',
                'phone_secondary' => '402-555-0702',
                'email' => 'amanda@bluegrassdrywall.com',
                'address' => '2700 S 70th St, Lincoln, NE 68506',
                'specialty' => 'Drywall',
                'insurance_company' => 'Hartford',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Also does interior painting.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Timber Ridge Flooring',
                'contact_name' => 'Kevin Nash',
                'phone' => '402-555-0801',
                'phone_secondary' => null,
                'email' => 'kevin@timberridgeflooring.com',
                'address' => '330 N Cotner Blvd, Lincoln, NE 68505',
                'specialty' => 'Flooring',
                'insurance_company' => 'Allstate',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Hardwood, tile, and LVP installs.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Midwest Masonry Inc.',
                'contact_name' => 'Carlos Vega',
                'phone' => '402-555-0901',
                'phone_secondary' => '402-555-0902',
                'email' => 'carlos@midwestmasonry.com',
                'address' => '615 S 48th St, Lincoln, NE 68510',
                'specialty' => 'Masonry',
                'insurance_company' => 'State Farm',
                'has_construction_license' => true,
                'license_number' => 'NE-MS-34456',
                'notes' => 'Brick, block, and stone work.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Flatwater Insulation',
                'contact_name' => 'Paul Simmons',
                'phone' => '402-555-1001',
                'phone_secondary' => null,
                'email' => 'paul@flatwaterinsulation.com',
                'address' => '1100 High St, Lincoln, NE 68502',
                'specialty' => 'Insulation',
                'insurance_company' => 'Progressive',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Spray foam and batt insulation.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Capital City Windows',
                'contact_name' => 'Sandra Mills',
                'phone' => '402-555-1101',
                'phone_secondary' => '402-555-1102',
                'email' => 'sandra@capitalcitywindows.com',
                'address' => '5600 O St, Lincoln, NE 68510',
                'specialty' => 'Windows & Doors',
                'insurance_company' => 'Travelers',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => null,
                'is_active' => true,
            ],
            [
                'company_name' => 'Sandhills Steel Fabrication',
                'contact_name' => 'Dale Owens',
                'phone' => '402-555-1201',
                'phone_secondary' => null,
                'email' => 'dale@sandhillssteel.com',
                'address' => '890 Fallbrook Blvd, Lincoln, NE 68521',
                'specialty' => 'Steel & Metal Work',
                'insurance_company' => 'Zurich',
                'has_construction_license' => true,
                'license_number' => 'NE-ST-61120',
                'notes' => 'Railings, beams, and custom steel.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Panorama Painting Co.',
                'contact_name' => 'Luis Torres',
                'phone' => '402-555-1301',
                'phone_secondary' => '402-555-1302',
                'email' => 'luis@panoramapainting.com',
                'address' => '2020 N 1st St, Lincoln, NE 68521',
                'specialty' => 'Painting',
                'insurance_company' => 'CNA',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Interior and exterior. Fast turnaround.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Husker Excavation & Grading',
                'contact_name' => 'Randy Kowalski',
                'phone' => '402-555-1401',
                'phone_secondary' => null,
                'email' => 'randy@huskerexcavation.com',
                'address' => '6700 NW 12th St, Lincoln, NE 68521',
                'specialty' => 'Excavation',
                'insurance_company' => 'Nationwide',
                'has_construction_license' => true,
                'license_number' => 'NE-EX-49302',
                'notes' => null,
                'is_active' => true,
            ],
            [
                'company_name' => 'Precision Tile Works',
                'contact_name' => 'Maria Fuentes',
                'phone' => '402-555-1501',
                'phone_secondary' => '402-555-1502',
                'email' => 'maria@precisiontile.com',
                'address' => '3400 Pioneers Blvd, Lincoln, NE 68502',
                'specialty' => 'Tile & Stone',
                'insurance_company' => 'Liberty Mutual',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Kitchen backsplash, bathroom tile, flooring.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Blue River Landscaping',
                'contact_name' => 'Greg Patterson',
                'phone' => '402-555-1601',
                'phone_secondary' => null,
                'email' => 'greg@blueriverlandscaping.com',
                'address' => '1750 S Coddington Ave, Lincoln, NE 68522',
                'specialty' => 'Landscaping',
                'insurance_company' => 'Allstate',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => null,
                'is_active' => true,
            ],
            [
                'company_name' => 'NE Foundation Repair',
                'contact_name' => 'Frank Larson',
                'phone' => '402-555-1701',
                'phone_secondary' => '402-555-1702',
                'email' => 'frank@nefoundationrepair.com',
                'address' => '4100 Adams St, Lincoln, NE 68504',
                'specialty' => 'Foundation',
                'insurance_company' => 'Hartford',
                'has_construction_license' => true,
                'license_number' => 'NE-FN-82234',
                'notes' => 'Cracks, waterproofing, piering.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Platte Valley Cabinets',
                'contact_name' => 'Nancy Chang',
                'phone' => '402-555-1801',
                'phone_secondary' => null,
                'email' => 'nancy@plattevalleycabinets.com',
                'address' => '880 N 48th St, Lincoln, NE 68504',
                'specialty' => 'Cabinets & Millwork',
                'insurance_company' => 'State Farm',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Custom and semi-custom kitchen/bath cabinets.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Loup River Demolition',
                'contact_name' => 'Chad Morris',
                'phone' => '402-555-1901',
                'phone_secondary' => '402-555-1902',
                'email' => 'chad@loupriverdemolition.com',
                'address' => '2500 NW 56th St, Lincoln, NE 68524',
                'specialty' => 'Demolition',
                'insurance_company' => 'Zurich',
                'has_construction_license' => true,
                'license_number' => 'NE-DM-30018',
                'notes' => null,
                'is_active' => true,
            ],
            [
                'company_name' => 'Tri-State Waterproofing',
                'contact_name' => 'Hector Rios',
                'phone' => '402-555-2001',
                'phone_secondary' => null,
                'email' => 'hector@tristatewaterproofing.com',
                'address' => '1320 Calvert St, Lincoln, NE 68502',
                'specialty' => 'Waterproofing',
                'insurance_company' => 'CNA',
                'has_construction_license' => true,
                'license_number' => 'NE-WP-55671',
                'notes' => 'Basements, crawlspaces, flat roofs.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Big Red Fencing',
                'contact_name' => 'Aaron Wells',
                'phone' => '402-555-2101',
                'phone_secondary' => '402-555-2102',
                'email' => 'aaron@bigredfencing.com',
                'address' => '9200 Andermatt Dr, Lincoln, NE 68526',
                'specialty' => 'Fencing',
                'insurance_company' => 'Progressive',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Wood, vinyl, chain-link, ornamental iron.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Summit Stucco & Plaster',
                'contact_name' => 'Elena Moreno',
                'phone' => '402-555-2201',
                'phone_secondary' => null,
                'email' => 'elena@summitstucco.com',
                'address' => '760 S 27th St, Lincoln, NE 68510',
                'specialty' => 'Stucco & Plaster',
                'insurance_company' => 'Travelers',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => null,
                'is_active' => false,
            ],
            [
                'company_name' => 'Ozark Deck Builders',
                'contact_name' => 'Tyler Grant',
                'phone' => '402-555-2301',
                'phone_secondary' => '402-555-2302',
                'email' => 'tyler@ozarkdeckbuilders.com',
                'address' => '4230 Calvert St, Lincoln, NE 68506',
                'specialty' => 'Decks & Outdoor Structures',
                'insurance_company' => 'Nationwide',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => 'Composite and wood decks, pergolas.',
                'is_active' => true,
            ],
            [
                'company_name' => 'Iron Horse Welding',
                'contact_name' => 'Brett Nguyen',
                'phone' => '402-555-2401',
                'phone_secondary' => null,
                'email' => 'brett@ironhorsewelding.com',
                'address' => '350 W Cornhusker Hwy, Lincoln, NE 68521',
                'specialty' => 'Welding & Fabrication',
                'insurance_company' => 'Hartford',
                'has_construction_license' => false,
                'license_number' => null,
                'notes' => null,
                'is_active' => false,
            ],
            [
                'company_name' => 'Platte Valley Septic & Drain',
                'contact_name' => 'Glen Hoffman',
                'phone' => '402-555-2501',
                'phone_secondary' => '402-555-2502',
                'email' => 'glen@plattevalleyseptic.com',
                'address' => '5050 NE 14th St, Lincoln, NE 68521',
                'specialty' => 'Septic & Drain',
                'insurance_company' => 'Liberty Mutual',
                'has_construction_license' => true,
                'license_number' => 'NE-SD-70034',
                'notes' => 'Septic installs, drain cleaning, sewer repair.',
                'is_active' => true,
            ],
        ];

        foreach ($contractors as $data) {
            Contractor::create($data);
        }
    }
}
